"""Episodic Boolean rule induction; teachers exist only in data/evaluation code.

An input is an n-bit vector. Each task depends on 1--4 hidden coordinates.
All labels are procedural, not generated by a language model. The learner sees
only support x/y and query x, never the coordinates, truth table, or rule id.
"""
import hashlib
import itertools
import json
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parent
DATA = ROOT / 'data/stage5'
SEED = 2026091605


def truth_values(code, k):
    return [(code >> i) & 1 for i in range(2 ** k)]


def essential(code, k):
    table = truth_values(code, k)
    return all(any(table[i] != table[i ^ (1 << j)] for i in range(2 ** k)) for j in range(k))


def rule_id(n, indices, table):
    return f'{n}:' + ','.join(map(str, indices)) + ':' + ''.join(map(str, table))


def rules(n, family):
    if family == 'unary':
        k, tables = 1, [[0, 1], [1, 0]]
    elif family == 'binary_nonparity':
        k = 2
        tables = [truth_values(c, 2) for c in range(16) if essential(c, 2) and c not in [6, 9]]
    elif family.startswith('parity'):
        k = int(family[-1])
        base = [i.bit_count() % 2 for i in range(2 ** k)]
        tables = [base, [1 - v for v in base]]
    elif family == 'majority3':
        k = 3
        base = [int(i.bit_count() >= 2) for i in range(8)]
        tables = [base, [1 - v for v in base]]
    elif family == 'multiplexer3':
        k = 3
        # Each coordinate may be selector; both output polarities are included.
        tables = []
        for selector in range(3):
            a, b = [j for j in range(3) if j != selector]
            for swap in [False, True]:
                base = [((i >> (a if bool((i >> selector) & 1) == swap else b)) & 1) for i in range(8)]
                tables.extend([base, [1 - v for v in base]])
        tables = [list(t) for t in sorted(set(map(tuple, tables)))]
    else:
        raise ValueError(family)
    return [dict(id=rule_id(n, ix, tab), n=n, indices=list(ix), table=tab, family=family)
            for ix in itertools.combinations(range(n), k) for tab in tables]


def oracle(rule, xs):
    # Table lookup is the procedural teacher, not called by model/memory/CLI.
    weights = 1 << np.arange(len(rule['indices']))
    indices = np.asarray(xs, dtype=np.int64)[:, rule['indices']] @ weights
    return np.asarray(rule['table'], dtype=np.int64)[indices]


def episode(rule, rng, k, q, episode_id):
    values = rng.choice(2 ** rule['n'], k + q, replace=False)
    xs = ((values[:, None] >> np.arange(rule['n'])) & 1).astype(int)
    ys = oracle(rule, xs)
    return dict(id=episode_id, rule_id=rule['id'], family=rule['family'], n=rule['n'],
                support_x=xs[:k].tolist(), support_y=ys[:k].tolist(),
                query_x=xs[k:].tolist(), query_y=ys[k:].tolist())


def save_rows(name, rows):
    path = DATA / f'{name}.jsonl'
    path.write_text(''.join(json.dumps(row, separators=(',', ':')) + '\n' for row in rows))
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load(split):
    return [json.loads(line) for line in (DATA / f'{split}.jsonl').read_text().splitlines()]


def generate():
    if (DATA / 'manifest.json').exists():
        raise FileExistsError('Existing stage 5 dataset is immutable; use a new stage for redesign.')
    DATA.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(SEED)
    all_rules = rules(8, 'unary') + rules(8, 'binary_nonparity')
    # Stratify by truth table, splitting whole rules (not just input pairs).
    train, val, test = [], [], []
    for tab in sorted(set(tuple(r['table']) for r in all_rules)):
        group = [r for r in all_rules if tuple(r['table']) == tab]
        order = rng.permutation(len(group))
        hold = max(1, len(group) // 8)
        val.extend(group[i] for i in order[:hold])
        test.extend(group[i] for i in order[hold:2 * hold])
        train.extend(group[i] for i in order[2 * hold:])
    registry = {r['id']: r for r in all_rules}
    partitions = dict(train=[r['id'] for r in train], val=[r['id'] for r in val], test=[r['id'] for r in test])
    splits = {}
    splits['train'] = [episode(train[int(rng.integers(len(train)))], rng, [8, 16, 32][i % 3], 16, f'train-{i}')
                       for i in range(6000)]
    for name, group, repeats in [('val', val, 6), ('test', test, 8)]:
        splits[name] = [episode(r, rng, [8, 16, 32][i % 3] if name == 'val' else 32, 32, f'{name}-{j}-{i}')
                        for j, r in enumerate(group) for i in range(repeats)]
    for family in ['parity2', 'parity3', 'majority3', 'multiplexer3', 'parity4']:
        group = rules(8, family)
        registry.update({r['id']: r for r in group})
        selected = [group[i] for i in rng.choice(len(group), min(len(group), 128), replace=False)]
        partitions[family] = [r['id'] for r in selected]
        splits[family] = [episode(r, rng, 32, 32, f'{family}-{j}-{i}')
                          for j, r in enumerate(selected) for i in range(2)]
    # Paired support-size curve. These episodes share queries and nested supports.
    selected = [registry[rid] for rid in partitions['parity3'][:64]]
    splits['support_curve'] = []
    for i, rule in enumerate(selected):
        base = episode(rule, rng, 64, 32, f'curve-{i}')
        for k in [4, 8, 16, 32, 64]:
            row = dict(base, id=f'curve-{i}-k{k}', pair_id=f'curve-{i}', support_x=base['support_x'][:k], support_y=base['support_y'][:k])
            splits['support_curve'].append(row)
    group = rules(12, 'parity3')
    selected = [group[i] for i in rng.choice(len(group), 128, replace=False)]
    registry.update({r['id']: r for r in selected})
    partitions['wide'] = [r['id'] for r in selected]
    splits['wide'] = [episode(r, rng, 32, 32, f'wide-{i}') for i, r in enumerate(selected)]
    hashes = {name: save_rows(name, rows) for name, rows in splits.items()}
    (DATA / 'rules.json').write_text(json.dumps(registry, indent=2))
    hashes['rules'] = hashlib.sha256((DATA / 'rules.json').read_bytes()).hexdigest()
    manifest = dict(seed=SEED, hashes=hashes, counts={name: len(rows) for name, rows in splits.items()},
                    rule_partitions=partitions, train_families=['unary', 'binary_nonparity'],
                    heldout_families=['parity2', 'parity3', 'majority3', 'multiplexer3', 'parity4'],
                    feature_limit_in_memory=3, procedural_teacher=True, final_test_open=False,
                    notes=['Support and query inputs are disjoint within every episode.',
                           'Rule identities are disjoint across train/val/test; final stress splits may share final rules.',
                           'Parity4 lies outside the supplied maximum-3-coordinate memory hypothesis class.',
                           'Random supports may be ambiguous: score and report version-space certainty separately.'])
    (DATA / 'manifest.json').write_text(json.dumps(manifest, indent=2))
    print(json.dumps(dict(counts=manifest['counts'], rules={k: len(v) for k, v in partitions.items()}), indent=2))


if __name__ == '__main__':
    generate()
