"""Procedural curriculum for ONE character model: arithmetic, logic, variables.

This module is a teacher/data generator, never imported by neural inference.
All examples and intermediate traces are generated by code, not an LLM.
"""
import hashlib
import json
from pathlib import Path
import random

ROOT = Path(__file__).resolve().parent
DATA = ROOT/'data/stage6'
SEED = 2026091706
HELD_PAIRS = {('xor','xor'),('not','not'),('and','or')}


def logic_value(tree):
    if isinstance(tree,int): return tree,[]
    op,*children=tree; evaluated=[logic_value(c) for c in children]
    vals=[v for v,t in evaluated]; trace=[s for v,t in evaluated for s in t]
    if op=='not': out=1-vals[0]
    elif op=='and': out=vals[0]&vals[1]
    elif op=='or': out=vals[0]|vals[1]
    elif op=='xor': out=vals[0]^vals[1]
    else: raise ValueError(op)
    return out,trace+[f'{op}={out}']


def logic_text(tree):
    return str(tree) if isinstance(tree,int) else tree[0]+'('+','.join(logic_text(c) for c in tree[1:])+')'


def pairs(tree):
    if isinstance(tree,int): return set()
    result=set()
    for child in tree[1:]:
        if not isinstance(child,int): result.add((tree[0],child[0]));result.update(pairs(child))
    return result


def tree_depth(tree):
    return 0 if isinstance(tree,int) else 1+max(tree_depth(c) for c in tree[1:])


def random_tree(rng,depth):
    if depth==0 or (depth>0 and rng.random()<.3): return rng.randrange(2)
    op=rng.choice(['and','or','xor','not'])
    return [op]+[random_tree(rng,depth-1) for _ in range(1 if op=='not' else 2)]


def logic_row(tree):
    answer,trace=logic_value(tree)
    return dict(family='logic',prompt='логика '+logic_text(tree),answer=str(answer),
                trace=';'.join(trace),difficulty=len(trace),spec=dict(tree=tree,depth=tree_depth(tree)))


def arithmetic_row(values):
    total=0;trace=[]
    for value in values:
        total+=value;trace.append(str(total))
    return dict(family='sum',prompt='сумма '+','.join(map(str,values)),answer=str(total),
                trace=','.join(trace),difficulty=len(values),spec=dict(values=values))


def program_row(initial,instructions,query):
    state=dict(initial);trace=[]
    initial_text=';'.join(f'{k}={v}' for k,v in initial)
    texts=[]
    for dst,left,op,right in instructions:
        a=state[left] if isinstance(left,str) else left
        b=state[right] if isinstance(right,str) else right
        if op=='+': value=(a+b)%10
        elif op=='-': value=(a-b)%10
        elif op=='*': value=(a*b)%10
        else: raise ValueError(op)
        state[dst]=value;trace.append(f'{dst}={value}')
        texts.append(f'{dst}=({left}{op}{right})%10')
    prompt='код '+initial_text+';'+';'.join(texts)+';?'+query
    return dict(family='code',prompt=prompt,answer=str(state[query]),trace=';'.join(trace),
                difficulty=len(instructions),spec=dict(initial=initial,instructions=instructions,query=query))


def random_program(rng,length,alias=False,names='abcd'):
    order=rng.sample(list(names),4);initial=[[name,rng.randrange(10)] for name in order]
    instructions=[]
    for i in range(length):
        dst=rng.choice(order);left=rng.choice(order) if rng.random()<.7 else rng.randrange(10)
        right=rng.choice(order) if rng.random()<.7 else rng.randrange(10)
        if alias and i==0: left=right=rng.choice(order)
        if not alias and isinstance(left,str) and left==right:
            right=rng.choice([n for n in order if n!=left])
        instructions.append([dst,left,rng.choice(['+','-','*']),right])
    written=list(dict.fromkeys(r[0] for r in instructions))
    query=rng.choice(written)
    return program_row(initial,instructions,query)


def completion(row,mode):
    return row['answer'] if mode=='direct' else row['trace']+'|'+row['answer']


def load(split):
    return [json.loads(line) for line in (DATA/f'{split}.jsonl').read_text().splitlines()]


def generate():
    if (DATA/'manifest.json').exists(): raise FileExistsError('Stage 6 data already frozen.')
    DATA.mkdir(parents=True,exist_ok=True);rng=random.Random(SEED);seen=set();splits={}
    def build(name,count,family,producer,bucket=None):
        rows=[];classes=[0,0];attempts=0
        while len(rows)<count:
            attempts+=1
            if attempts>max(200000,count*1000): raise RuntimeError((name,len(rows)))
            row=producer();prompt=row['prompt']
            if prompt in seen: continue
            if bucket is not None:
                partition=int.from_bytes(hashlib.sha256(prompt.encode()).digest()[:4],'little')%10
                if bucket=='train' and partition>=8: continue
                if bucket=='val' and partition!=8: continue
                if bucket=='test' and partition!=9: continue
            if row['family']=='logic':
                value=int(row['answer'])
                if classes[value]>=count//2: continue
                classes[value]+=1
            row['id']=f'{name}-{family}-{len(rows)}';rows.append(row);seen.add(prompt)
        return rows
    def normal_logic():
        while True:
            t=random_tree(rng,rng.randint(1,3))
            if isinstance(t,int) or pairs(t)&HELD_PAIRS: continue
            row=logic_row(t)
            if row['difficulty']<=7:return row
    for split,count in [('train',12000),('val',120),('test',240)]:
        split_rows=[]
        split_rows+=build(split,count,'sum',lambda:arithmetic_row([rng.randrange(100) for _ in range(rng.randint(2,6))]),split)
        # Finite small trees are fewer than numeric/program strings; permit depth
        # three with all bounded shapes, and use a smaller exact-unique corpus.
        logic_count=4000 if split=='train' else count
        split_rows+=build(split,logic_count,'logic',normal_logic,split)
        split_rows+=build(split,count,'code',lambda:random_program(rng,rng.randint(1,4)),split)
        rng.shuffle(split_rows);splits[split]=split_rows
    for split,lengths in [('long',[8,12]),('very_long',[24,32])]:
        rows=[]
        for length in lengths:
            rows+=build(split,60,f'sum{length}',lambda n=length:arithmetic_row([rng.randrange(10) for _ in range(n)]))
            rows+=build(split,60,f'code{length}',lambda n=length:random_program(rng,n))
        splits[split]=rows
    def composed_logic():
        while True:
            t=random_tree(rng,rng.randint(2,4))
            if not isinstance(t,int) and pairs(t)&HELD_PAIRS:
                row=logic_row(t)
                if row['difficulty']<=10:return row
    splits['composition']=build('composition',240,'logic',composed_logic)
    def deep_logic():
        # Chain-shaped trees test deep recursion while keeping token count linear.
        t=rng.randrange(2)
        for _ in range(rng.choice([8,12,16])):
            op=rng.choice(['and','or','xor','not'])
            t=[op,t] if op=='not' else [op,rng.randrange(2),t]
        return logic_row(t)
    splits['deep_logic']=build('deep_logic',240,'logic',deep_logic)
    splits['alias']=build('alias',240,'code',lambda:random_program(rng,rng.randint(2,4),alias=True))
    # Same programs under alpha-renaming: paired outputs, disjoint text strings.
    code_rows=[r for r in splits['test'] if r['family']=='code']
    rename=dict(zip('abcd','ijkl'));renamed=[]
    for row in code_rows:
        spec=row['spec'];initial=[[rename[k],v] for k,v in spec['initial']]
        instructions=[[rename[d],rename.get(a,a),op,rename.get(b,b)] for d,a,op,b in spec['instructions']]
        new=program_row(initial,instructions,rename[spec['query']]);new['id']='renamed-'+row['id'];new['paired_id']=row['id']
        assert new['prompt'] not in seen;seen.add(new['prompt']);renamed.append(new)
    splits['renamed']=renamed
    splits['large_values']=build('large_values',240,'sum',lambda:arithmetic_row([rng.randrange(100,1000) for _ in range(rng.randint(2,6))]))
    hashes={}
    for name,rows in splits.items():
        path=DATA/f'{name}.jsonl';path.write_text(''.join(json.dumps(r,ensure_ascii=False,separators=(',',':'))+'\n' for r in rows))
        hashes[name]=hashlib.sha256(path.read_bytes()).hexdigest()
    manifest=dict(seed=SEED,hashes=hashes,counts={k:len(v) for k,v in splits.items()},
                  train_counts={f:sum(r['family']==f for r in splits['train']) for f in ['sum','logic','code']},
                  held_operator_pairs=sorted(map(list,HELD_PAIRS)),train_registers='abcd',held_registers='ijkl',
                  procedural_labels=True,final_test_open=False,
                  notes=['One shared model receives text only, no parsed program or true state at inference.',
                         'Scratchpads provide additional intermediate supervision; equal updates do not equal supervised-target tokens.',
                         'All final input strings disjoint from training and validation; renamed is paired with ordinary test.',
                         'Long sums use small terms to limit value-range shift; very long programs also increase context length.',
                         'Formal Russian task prefixes are a controlled interface, not open-language understanding.'])
    (DATA/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2))
    print(json.dumps(dict(counts=manifest['counts'],train_counts=manifest['train_counts']),indent=2))


if __name__=='__main__':generate()
